/* Generated by bin2c */

extern unsigned char dualboot_install_ipod6g[5424];
extern unsigned char dualboot_install_ipodnano3g[5408];
extern unsigned char dualboot_uninstall_ipod6g[5040];
extern unsigned char dualboot_uninstall_ipodnano3g[5008];
